AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Jersey API - org.example::jersey-lambda
Resources:
  JerseyLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: org.example.StreamLambdaHandler::handleRequest
      Runtime: java8
      CodeUri: target/jersey-lambda-1.0-SNAPSHOT.jar
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 15
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  JerseyLambdaApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/messages'
    Export:
      Name: JerseyLambdaApi
#  JerseyLambdaMessageApi:
#    Description: URL for Message API
#    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}/amazonaws.com/Prod/messages'
#    Export:
#      Name: JerseyLambdaMessageApi